version: '3'

services:
 postgres:
  image: 'postgres:latest'

 redis:
  image: 'redis:latest'
 
 nginx:
  restart: always #we use restart policy to make sure that this server is working 100% since it's routing all of our trafic
  build:
    dockerfile: Dockerfile.dev
    context: ./nginx
  ports:
    - '3050:80' #80 is the port in docker we spicify it in ningx conf


 api:
  build:
   dockerfile: Dockerfile.dev
   context: ./server
  volumes:
   - /app/node_modules
   - ./server:/app
  environment:
   - REDIS_HOST= redis #host is the name of server
   - REDIS_PORT=6379 #we got port from docker hub
   - PGUSER=postgres #default for postgres 
   - PGHOST=postgres #default for postgres 
   - PGDATABASE=postgres #default for postgres 
   - PGPASSWORD=postgres_password #default for postgres 
   - PGPORT=5432 #we got post from docker hub
 
 client:
  build:
   dockerfile: Dockerfile.dev
   context: ./client
  volumes:
   - /app/node_modules
   - ./client:/app
 
 worker:
  build:
   dockerfile: Dockerfile.dev
   context: ./worker
  volumes:
   - /app/node_modules
   - ./worker:/app


   #to run docker-compose / docker-compose up and to force rebuild /docker-compose up --build