FROM nginx
COPY ./default.conf /etc/nginx/conf.d/default.conf 
#in above line we copy our conf to our docker by overwrite the defult one , we can have 
#different config file for production and refert it above